### ISSUE TITLE
Receive/handle deletion notifications from sdx-controller

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-lc#125]
This is the counterpart of https://github.com/atlanticwave-sdx/sdx-controller/issues/261 (SDX Controller should notify LC on connection deletions).

SDX Controller publishes connection information on message queue, which is received by the local controller.  The local controller should also receive connection teardown/deletion messages and handle them in a similar manner. 

Unless I'm missing something obvious. :-)

**Comment by YufengXin** [comment]
It's my understanding too. @congwang09 ?
My thought was that both depends on the consistent handling of the connection_id. 

Sajith presented some detailed info in this closed issue:
https://github.com/atlanticwave-sdx/sdx-controller/pull/225

Related to PCE issues?
https://github.com/atlanticwave-sdx/pce/issues/159
https://github.com/atlanticwave-sdx/pce/issues/180
https://github.com/atlanticwave-sdx/pce/issues/121

Do we need an implementation plan among us?

**Comment by YufengXin** [comment]
see this:

https://github.com/atlanticwave-sdx/pce/pull/188

**Comment by congwang09** [comment]
Completed
