### ISSUE TITLE
How to configure mongodb replica set on the new env variables schema for SDX-LC?

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-lc#153]
We used to have a more flexible way of configuring MongoDB connection parameters via the environment variable MONGODB_CONNSTRING.

That old config schema is used to configure the MongoDB replica set (multi-host connection schema).

What is the suggestion for such a config now?

As far as I could understand, PR #148 replaced the MONGODB_CONNSTRING with `MONGO_HOST`, `MONGO_PORT`, `MONGO_USER`, and `MONGO_PASS`, which made the config more restrictive in how we set up our MongoDB connection parameters.

Before, we could have something like: `mongodb://myDatabaseUser:D1fficultP%40ssw0rd @mongo1t:27027,mongo2t:27028,mongo3t:27029/?authSource=admin`

Now, we can always use creative workarounds to hack the new parameters, like using `MONGO_HOST=mongo1t:27027,mongo2t:27028,mongo3t` and then leaving the last node port to be completed by MONGO_PORT. However, I'm sure the workaround above is not the best practice.

Please advise!

**Comment by sajith** [comment]
Would adding support for `MONGODB_CONNSTRING` env var back help?

**Comment by sajith** [comment]
Also, does this affect only SDX LC?  Do you want a similar change in SDX Controller as well?
