### ISSUE TITLE
How to specify the mongo Database name for client connection ?

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-lc#155]
Similar to #153 it would be nice if we have a way of specifying the Database name for client connection using pymongo. When we used to have the mongo connection string, it was easy to have the DBNAME as part of if.

I see you are using the Mongo Root user to connect (https://github.com/atlanticwave-sdx/sdx-lc/blob/main/tox.ini#L60-L61), so that is probably why you didn't need to specify it before.

Please advise!

**Comment by sajith** [comment]
That still should be `DB_NAME`, I think?  (I did not write the DB code, so I am less familiar with the actual workings of it, but I _think_ that is the thing we are looking for.)

Also PR #154 would restore `MONGODB_CONNSTRING`, if that helps.

**Comment by italovalcy** [comment]
Hi @sajith you are right! that is true and PR #154 also fixed this issue. Sorry I didnt see this before and thanks for your information and help here!
