### ISSUE TITLE
SDX 1.c.iii RESTful endpoint to export topology to MEICAN

### ISSUE THREAD

**Issue by lmarinve** [atlanticwave-sdx/sdx-lc#62]
Created by Luis Marin Vera via monday.com integration. 🎉

**Comment by lmarinve** [comment]
MEICAN (label: epic_topo_export_meican): the SDX Controller should have a RESTful endpoint that exports the topology in MEICAN format. (Luis)

**Comment by YufengXin** [comment]
Not relevant.
