### ISSUE TITLE
Links published on MQ cause a crash

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-lc#90]
While working on https://github.com/atlanticwave-sdx/pce/pull/115, when a breakdown is published by sdx-controller, I see a crash on sdx-lc (see below for the backtrace).  I suspect that this is a decoding issue.  Notice that the data read from MQ is bytes (`MQ received message:b'{"ingress_port":...`), and so this line:

https://github.com/atlanticwave-sdx/sdx-lc/blob/bdbb4038095321b903dfd333fe63bb12095239e9/swagger_server/messaging/topic_queue_consumer.py#L87

... probably should be:

```python
        self.db_instance.add_key_value_pair_to_db(self.message_id, msg_json)
```

Backtrace:

```
sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:MQ received message:b'{"ingress_port": {"id": "urn:ogf:network:sdx:port:zaoxi:A1:2", "name": "Novi100:2", "short_name": null, "node": "urn:ogf:network:sdx:node:zaoxi:A1", "label_range": null, "status": null, "state": null, "private_attributes": null}, "egress_port": {"id": "urn:ogf:network:sdx:port:zaoxi:B1:1", "name": "Novi01:1", "node": "urn:ogf:network:sdx:node:zaoxi:B1", "short_name": "B1:1", "label_range": ["100-200", "10001"], "status": "up"}}'
sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:JSON message
sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Got connection message.
sdx-lc      | Exception in thread Thread-4:
sdx-lc      | Traceback (most recent call last):
sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
sdx-lc      |     self.run()
sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
sdx-lc      |     self.channel.start_consuming()                                                                                                                                   [0/1873]
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
sdx-lc      |     self._process_data_events(time_limit=None)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
sdx-lc      |     self.connection.process_data_events(time_limit=time_limit)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
sdx-lc      |     self._dispatch_channel_events()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
sdx-lc      |     impl_channel._get_cookie()._dispatch_events()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
sdx-lc      |     consumer_info.on_message_callback(self, evt.method,
sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 72, in callback
sdx-lc      |     self.handle_mq_msg(body)
sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 87, in handle_mq_msg
sdx-lc      |     self.db_instance.add_key_value_pair_to_db(self.message_id, msg_body)
sdx-lc      |   File "/usr/src/app/swagger_server/utils/db_utils.py", line 36, in add_key_value_pair_to_db
sdx-lc      |     obj = self.read_from_db(key)
sdx-lc      |   File "/usr/src/app/swagger_server/utils/db_utils.py", line 52, in read_from_db
sdx-lc      |     return self.sdxdb[self.db_name][self.config_table_name].find_one(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 1459, in find_one
sdx-lc      |     for result in cursor.limit(-1):
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
sdx-lc      |     if len(self.__data) or self._refresh():
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1165, in _refresh
sdx-lc      |     self.__send_message(q)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1052, in __send_message
sdx-lc      |     response = client._run_operation(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
sdx-lc      |     return func(self, *args, **kwargs)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1330, in _run_operation
sdx-lc      |     return self._retryable_read(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
sdx-lc      |     return func(self, *args, **kwargs)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1448, in _retryable_read
sdx-lc      |     return func(session, server, sock_info, read_pref)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1326, in _cmd
sdx-lc      |     return server.run_operation(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/server.py", line 100, in run_operation
sdx-lc      |     message = operation.get_message(read_preference, sock_info, use_cmd)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/message.py", line 388, in get_message
sdx-lc      |     request_id, msg, size, _ = _op_msg(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/message.py", line 692, in _op_msg
sdx-lc      |     return _op_msg_uncompressed(flags, command, identifier, docs, opts)
sdx-lc      | bson.errors.InvalidDocument: documents must have only string keys, key was 0
```

**Comment by sajith** [comment]
Probably the key is the problem?  Since `add_key_value_pair_to_db(key, val)` expects a string as key,

https://github.com/atlanticwave-sdx/sdx-lc/blob/bdbb4038095321b903dfd333fe63bb12095239e9/swagger_server/messaging/topic_queue_consumer.py#L87

should be:

```python
 self.db_instance.add_key_value_pair_to_db(str(self.message_id), msg_body) 
```

And then we get another error (from sdx-lc-1):

```
sdx-lc      | DEBUG:swagger_server.utils.db_utils:Adding key value pair to DB.
sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Save to database complete.
sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Message ID:0
sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Sending connection info to Kytos.
sdx-lc      | Exception in thread Thread-4:
sdx-lc      | Traceback (most recent call last):
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in _new_conn
sdx-lc      |     sock = connection.create_connection(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
sdx-lc      |     raise err
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
sdx-lc      |     sock.connect(sa)
sdx-lc      | ConnectionRefusedError: [Errno 111] Connection refused
sdx-lc      |
sdx-lc      | The above exception was the direct cause of the following exception:
sdx-lc      |
sdx-lc      | Traceback (most recent call last):
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
sdx-lc      |     response = self._make_request(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 496, in _make_request
sdx-lc      |     conn.request(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 388, in request
sdx-lc      |     self.endheaders()
sdx-lc      |   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
sdx-lc      |     self._send_output(message_body, encode_chunked=encode_chunked)
sdx-lc      |   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
sdx-lc      |     self.send(msg)
sdx-lc      |   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
sdx-lc      |     self.connect()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 236, in connect
sdx-lc      |     self.sock = self._new_conn()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 215, in _new_conn
sdx-lc      |     raise NewConnectionError(
sdx-lc      | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc4f42caa60>: Failed to establish a new connection: [Errno 111] Connection refused
sdx-lc      |
sdx-lc      | The above exception was the direct cause of the following exception:
sdx-lc      |
sdx-lc      | Traceback (most recent call last):
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
sdx-lc      |     resp = conn.urlopen(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
sdx-lc      |     retries = retries.increment(
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
sdx-lc      |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
sdx-lc      | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.201.205', port=8088): Max retries exceeded with url: /SDX-LC/1.0.0/connection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc4f42caa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
sdx-lc      |
sdx-lc      | During handling of the above exception, another exception occurred:
sdx-lc      |
sdx-lc      | Traceback (most recent call last):
sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
sdx-lc      |     self.run()
sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
sdx-lc      |     self._target(*self._args, **self._kwargs)
sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 131, in start_consumer
sdx-lc      |     self.channel.start_consuming()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
sdx-lc      |     self._process_data_events(time_limit=None)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
sdx-lc      |     self.connection.process_data_events(time_limit=time_limit)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
sdx-lc      |     self._dispatch_channel_events()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
sdx-lc      |     impl_channel._get_cookie()._dispatch_events()
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
sdx-lc      |     consumer_info.on_message_callback(self, evt.method,
sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 72, in callback
sdx-lc      |     self.handle_mq_msg(body)
sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 93, in handle_mq_msg
sdx-lc      |     r = requests.post(str(KYTOS_URL), json=msg_json)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 115, in post
sdx-lc      |     return request("post", url, data=data, json=json, **kwargs)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
sdx-lc      |     return session.request(method=method, url=url, **kwargs)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
sdx-lc      |     resp = self.send(prep, **send_kwargs)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
sdx-lc      |     r = adapter.send(request, **kwargs)
sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
sdx-lc      |     raise ConnectionError(e, request=request)
sdx-lc      | requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.201.205', port=8088): Max retries exceeded with url: /SDX-LC/1.0.0/connection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc4f42caa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
sdx-lc      | INFO:werkzeug:64.225.74.178 - - [25/May/2023 21:02:15] "GET / HTTP/1.1" 404 -
sdx-lc      | INFO:werkzeug:64.225.74.178 - - [25/May/2023 21:02:16] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by congwang09** [comment]
> While working on [atlanticwave-sdx/pce#115](https://github.com/atlanticwave-sdx/pce/pull/115), when a breakdown is published by sdx-controller, I see a crash on sdx-lc (see below for the backtrace). I suspect that this is a decoding issue. Notice that the data read from MQ is bytes (`MQ received message:b'{"ingress_port":...`), and so this line:
> 
> https://github.com/atlanticwave-sdx/sdx-lc/blob/bdbb4038095321b903dfd333fe63bb12095239e9/swagger_server/messaging/topic_queue_consumer.py#L87
> 
> ... probably should be:
> 
> ```python
>         self.db_instance.add_key_value_pair_to_db(self.message_id, msg_json)
> ```
> 
> Backtrace:
> 
> ```
> sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:MQ received message:b'{"ingress_port": {"id": "urn:ogf:network:sdx:port:zaoxi:A1:2", "name": "Novi100:2", "short_name": null, "node": "urn:ogf:network:sdx:node:zaoxi:A1", "label_range": null, "status": null, "state": null, "private_attributes": null}, "egress_port": {"id": "urn:ogf:network:sdx:port:zaoxi:B1:1", "name": "Novi01:1", "node": "urn:ogf:network:sdx:node:zaoxi:B1", "short_name": "B1:1", "label_range": ["100-200", "10001"], "status": "up"}}'
> sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:JSON message
> sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Got connection message.
> sdx-lc      | Exception in thread Thread-4:
> sdx-lc      | Traceback (most recent call last):
> sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
> sdx-lc      |     self.run()
> sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
> sdx-lc      |     self.channel.start_consuming()                                                                                                                                   [0/1873]
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
> sdx-lc      |     self._process_data_events(time_limit=None)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
> sdx-lc      |     self.connection.process_data_events(time_limit=time_limit)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
> sdx-lc      |     self._dispatch_channel_events()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
> sdx-lc      |     impl_channel._get_cookie()._dispatch_events()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
> sdx-lc      |     consumer_info.on_message_callback(self, evt.method,
> sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 72, in callback
> sdx-lc      |     self.handle_mq_msg(body)
> sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 87, in handle_mq_msg
> sdx-lc      |     self.db_instance.add_key_value_pair_to_db(self.message_id, msg_body)
> sdx-lc      |   File "/usr/src/app/swagger_server/utils/db_utils.py", line 36, in add_key_value_pair_to_db
> sdx-lc      |     obj = self.read_from_db(key)
> sdx-lc      |   File "/usr/src/app/swagger_server/utils/db_utils.py", line 52, in read_from_db
> sdx-lc      |     return self.sdxdb[self.db_name][self.config_table_name].find_one(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 1459, in find_one
> sdx-lc      |     for result in cursor.limit(-1):
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next
> sdx-lc      |     if len(self.__data) or self._refresh():
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1165, in _refresh
> sdx-lc      |     self.__send_message(q)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1052, in __send_message
> sdx-lc      |     response = client._run_operation(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
> sdx-lc      |     return func(self, *args, **kwargs)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1330, in _run_operation
> sdx-lc      |     return self._retryable_read(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
> sdx-lc      |     return func(self, *args, **kwargs)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1448, in _retryable_read
> sdx-lc      |     return func(session, server, sock_info, read_pref)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1326, in _cmd
> sdx-lc      |     return server.run_operation(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/server.py", line 100, in run_operation
> sdx-lc      |     message = operation.get_message(read_preference, sock_info, use_cmd)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/message.py", line 388, in get_message
> sdx-lc      |     request_id, msg, size, _ = _op_msg(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pymongo/message.py", line 692, in _op_msg
> sdx-lc      |     return _op_msg_uncompressed(flags, command, identifier, docs, opts)
> sdx-lc      | bson.errors.InvalidDocument: documents must have only string keys, key was 0
> ```

This should be fixed in this [PR](https://github.com/atlanticwave-sdx/sdx-lc/pull/91)

**Comment by congwang09** [comment]
> Probably the key is the problem? Since `add_key_value_pair_to_db(key, val)` expects a string as key,
> 
> https://github.com/atlanticwave-sdx/sdx-lc/blob/bdbb4038095321b903dfd333fe63bb12095239e9/swagger_server/messaging/topic_queue_consumer.py#L87
> 
> should be:
> 
> ```python
>  self.db_instance.add_key_value_pair_to_db(str(self.message_id), msg_body) 
> ```
> 
> And then we get another error (from sdx-lc-1):
> 
> ```
> sdx-lc      | DEBUG:swagger_server.utils.db_utils:Adding key value pair to DB.
> sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Save to database complete.
> sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Message ID:0
> sdx-lc      | INFO:swagger_server.messaging.topic_queue_consumer:Sending connection info to Kytos.
> sdx-lc      | Exception in thread Thread-4:
> sdx-lc      | Traceback (most recent call last):
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in _new_conn
> sdx-lc      |     sock = connection.create_connection(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
> sdx-lc      |     raise err
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
> sdx-lc      |     sock.connect(sa)
> sdx-lc      | ConnectionRefusedError: [Errno 111] Connection refused
> sdx-lc      |
> sdx-lc      | The above exception was the direct cause of the following exception:
> sdx-lc      |
> sdx-lc      | Traceback (most recent call last):
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
> sdx-lc      |     response = self._make_request(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 496, in _make_request
> sdx-lc      |     conn.request(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 388, in request
> sdx-lc      |     self.endheaders()
> sdx-lc      |   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
> sdx-lc      |     self._send_output(message_body, encode_chunked=encode_chunked)
> sdx-lc      |   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
> sdx-lc      |     self.send(msg)
> sdx-lc      |   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
> sdx-lc      |     self.connect()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 236, in connect
> sdx-lc      |     self.sock = self._new_conn()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 215, in _new_conn
> sdx-lc      |     raise NewConnectionError(
> sdx-lc      | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc4f42caa60>: Failed to establish a new connection: [Errno 111] Connection refused
> sdx-lc      |
> sdx-lc      | The above exception was the direct cause of the following exception:
> sdx-lc      |
> sdx-lc      | Traceback (most recent call last):
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
> sdx-lc      |     resp = conn.urlopen(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
> sdx-lc      |     retries = retries.increment(
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
> sdx-lc      |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
> sdx-lc      | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.201.205', port=8088): Max retries exceeded with url: /SDX-LC/1.0.0/connection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc4f42caa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
> sdx-lc      |
> sdx-lc      | During handling of the above exception, another exception occurred:
> sdx-lc      |
> sdx-lc      | Traceback (most recent call last):
> sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
> sdx-lc      |     self.run()
> sdx-lc      |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
> sdx-lc      |     self._target(*self._args, **self._kwargs)
> sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 131, in start_consumer
> sdx-lc      |     self.channel.start_consuming()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
> sdx-lc      |     self._process_data_events(time_limit=None)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
> sdx-lc      |     self.connection.process_data_events(time_limit=time_limit)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
> sdx-lc      |     self._dispatch_channel_events()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
> sdx-lc      |     impl_channel._get_cookie()._dispatch_events()
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
> sdx-lc      |     consumer_info.on_message_callback(self, evt.method,
> sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 72, in callback
> sdx-lc      |     self.handle_mq_msg(body)
> sdx-lc      |   File "/usr/src/app/swagger_server/messaging/topic_queue_consumer.py", line 93, in handle_mq_msg
> sdx-lc      |     r = requests.post(str(KYTOS_URL), json=msg_json)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 115, in post
> sdx-lc      |     return request("post", url, data=data, json=json, **kwargs)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
> sdx-lc      |     return session.request(method=method, url=url, **kwargs)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
> sdx-lc      |     resp = self.send(prep, **send_kwargs)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
> sdx-lc      |     r = adapter.send(request, **kwargs)
> sdx-lc      |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
> sdx-lc      |     raise ConnectionError(e, request=request)
> sdx-lc      | requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.201.205', port=8088): Max retries exceeded with url: /SDX-LC/1.0.0/connection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc4f42caa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
> sdx-lc      | INFO:werkzeug:64.225.74.178 - - [25/May/2023 21:02:15] "GET / HTTP/1.1" 404 -
> sdx-lc      | INFO:werkzeug:64.225.74.178 - - [25/May/2023 21:02:16] "GET /favicon.ico HTTP/1.1" 404 -
> ```

This is normal, because the sdx-lc is trying to connect to kytos, but no kytos server is running.

**Comment by sajith** [comment]
> This is normal, because the sdx-lc is trying to connect to kytos, but no kytos server is running.

If communication failure with Kytos is expected (because of whatever reason), perhaps it is better to catch and log the exception?

**Comment by YufengXin** [comment]
I agree. LC should catch this and return gracefully. In general, we should avoid Exceptions as much as possible
